# -*- coding: utf-8 -*-
"""task 3(3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p9lHWwIhM7GsqnP4JImtn3iC2LbY52kb
"""

!pip install -q openai

import os
from google.colab import userdata

os.environ["HF_TOKEN"] = userdata.get("HF_TOKEN")

from openai import OpenAI
import os

client = OpenAI(
    base_url="https://router.huggingface.co/v1",
    api_key=os.environ["HF_TOKEN"],
)

completion = client.chat.completions.create(
    model="deepseek-ai/DeepSeek-V3.2:novita",
    messages=[
        {
            "role": "user",
            "content": "What is the capital of France?"
        }
    ],
)

print(completion.choices[0].message.content)