# -*- coding: utf-8 -*-
"""task2(3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XeTmirKeBF2IngVYGJ_bOTgoeP_yICJH
"""

!pip install transformers torch

from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

prompt = "AI will change the world because"

result = generator(
    prompt,
    max_length=40,
    num_return_sequences=2
)

print(result)