# -*- coding: utf-8 -*-
"""task 5(3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OmUjFVMM02mvHGRs572BPfYgMGYrLqWL
"""

from openai import OpenAI
import os
from google.colab import userdata

os.environ["HF_TOKEN"] = userdata.get('HF_TOKEN')
client = OpenAI(
    base_url = "https://router.huggingface.co/v1",
    api_key = os.environ["HF_TOKEN"],
)
conversation = []
print("AI Chat (type 'exit' to end)")

while True:
  user_input = input("You: ")
  if user_input.lower() == "exit":
    print("Chat ended.")
    break
  conversation.append({"role": "user", "content": user_input})

  completion = client.chat.completions.create(
    model = "deepseek-ai/DeepSeek-V3.2:novita",
    messages = conversation)

  ai_response = completion.choices[0].message.content
  print(f"AI: {ai_response}")
  conversation.append({"role": "assistant", "content": ai_response})