# -*- coding: utf-8 -*-
"""task4(3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18XyxcLI_KpquYPvuo9ftovDjNc4bGRVO
"""

from openai import OpenAI
import os
from google.colab import userdata

os.environ["HF_TOKEN"] = userdata.get("HF_TOKEN")

client = OpenAI(
    base_url="https://router.huggingface.co/v1",
    api_key=os.environ["HF_TOKEN"],
)

template = "Explain {topic} in simple words. Do not use Markdown or formatting, just plain text."

topics = ["Machine Learning", "Quantum Computing", "Blockchain"]

for topic in topics:
    prompt = template.format(topic=topic)

    completion = client.chat.completions.create(
        model="deepseek-ai/DeepSeek-V3.2:novita",
        messages=[{"role": "user", "content": prompt}]
    )

    response = completion.choices[0].message.content
    print(f"Topic: {topic}\nResponse: {response}\n")