# -*- coding: utf-8 -*-
"""task6(3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FYH7aP6PDiGWrSUkjILx4GeEQjx0PNtx
"""

from openai import OpenAI
import os

text_client = OpenAI(
    base_url="https://router.huggingface.co/v1",
    api_key=os.environ["HF_TOKEN"],
)

text_prompt = """
Describe a cute little robot watering flowers in a sunny garden,
including the robot’s appearance, the colorful flowers, and the cheerful atmosphere.
"""

completion = text_client.chat.completions.create(
    model="deepseek-ai/DeepSeek-V3.2:novita",
    messages=[{"role": "user", "content": text_prompt}],
)

generated_text = completion.choices[0].message.content
print("Generated Text:\n", generated_text)

from huggingface_hub import InferenceClient
from IPython.display import display

image_client = InferenceClient(
    provider="nebius",
    api_key=os.environ["HF_TOKEN"],
)

image_prompt = "Cute little robot watering flowers in a sunny garden, colorful flowers, cheerful atmosphere, cartoon style, warm sunlight"

image = image_client.text_to_image(
    image_prompt,
    model="black-forest-labs/FLUX.1-dev",
)

image.save("robot_garden.png")
display(image)